[env]
SQLALCHEMY_DATABASE_URL = "sqlite:///./tutor_software.db"
AUTH_SECRET_KEY = "clave_secreta_tutor_software_2025"
ALGORITHM = "HS256"

[build]
command = "python -m pip install -r requirements.txt"

[run]
command = "python app/main.py"
